/*
This file displays the migration component. 
It allows users to migrate their PRTC tokens to Zaar tokens.
*/
import Image from "next/image";
import Link from "next/link";
import { parseEther } from "viem";
import { useAccount } from "wagmi";
import { waitForTransactionReceipt } from "@wagmi/core";
import toast, { Toaster } from "react-hot-toast";
import { formatEther } from "viem";
import React, { useEffect, useState } from "react";
import {
  useSimulateZaarflipFlip,
  useSimulateZaarflipAddAcceptedToken,
} from "@/generated";
import { writeContract } from "@wagmi/core";
import { useWriteZaarflipFlip } from "@/generated";
import { config } from "@/config";
import { abi } from "@/abis/abi";
import { Header } from "@/components/header";
import { HomePageBanner } from "@/components/HomePageBanner";

const Home: React.FC = () => {
  return (
    <div>
      <HomePageBanner />
      <div className="flex flex-col items-center relative">
        <div className="absolute reflection-gradient w-[904px] h-[200px] rounded-full opacity-50 -z-10 blur-xl top-[430px]"></div>
        <Image
          height={800}
          width={800}
          src="/old-zaar-coins/zaar-flip-heads.png"
          alt="Zaar-flip coin"
          className="w-[430px] mt-24"
        />
        <div className="text-[40px] mt-8 text-white/40">THE FUN NETWORK</div>
      </div>
      <div className="flex flex-col w-full items-center text-white text-lg mt-10">
        Choose your next move
        <svg
          stroke="currentColor"
          fill="currentColor"
          strokeWidth="0"
          viewBox="0 0 512 512"
          height="1em"
          width="1em"
          xmlns="http://www.w3.org/2000/svg"
          className={`transition-transform duration-300 rotate-180 scale-75`}
        >
          <path d="M233.4 105.4c12.5-12.5 32.8-12.5 45.3 0l192 192c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L256 173.3 86.6 342.6c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3l192-192z"></path>
        </svg>
        <div className="flex w-full justify-center gap-10 my-10">
          <div className="flex flex-col items-center p-5 bg-dark-gray rounded w-[400px] h-[300px]">
            <Link
              href="/zaar-flip"
              className="hover:cursor-pointer transition duration-300 hover:scale-105"
            >
              <Image
                src="/logo.png"
                alt="Zaar Flip Logo"
                width={105}
                height={40}
                className="mb-2 text-white w-[200px]"
              />
            </Link>
            Be the house! Take the other side of the wager by depositing INIT
            into the pool. Your deposit may accrue rewards generated by protocol
            revenues. But be aware! Deposits may also lose value, if and when
            there are a large amount of user payouts.
          </div>
          <div className="flex flex-col items-center p-5 bg-dark-gray rounded w-[400px] h-[300px]">
            <Link
              href="/zlinko"
              className="hover:cursor-pointer transition duration-300 hover:scale-105"
            >
              <Image
                src="/zlinko/zaar-zlinko.png"
                alt="Zaar Zlinko Logo"
                width={105}
                height={40}
                className="mt-5 mb-9 text-white w-[200px]"
              />
            </Link>
            Be the house! Take the other side of the wager by depositing INIT
            into the pool. Your deposit may accrue rewards generated by protocol
            revenues. But be aware! Deposits may also lose value, if and when
            there are a large amount of user payouts.
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
